# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd43efb571ff6fcf0a1232ca0e780e540849cea62f2ae00789632a6949aeac877bbd28a125dbf1df0eddbe78951b33377242a589f61c79fddb09c261806431f

test:
  secret_key_base: 245a7bc09665f0f51792cc6e31fdb64d4f21508b3d31eb8f2f88def9a4f9575272e33ad250117a198336f317ffd52475aacefed49bd129d89b51f611950f05c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
